Repository sieuno3o/GameGenie, pull requests merged in 2024-05, with the labels that each got.

#4 GG-BE community 카테고리 필드 , 로그인 인증 구현
  backend/accounts/migrations/0001_initial.py
  backend/community/migrations/0001_initial.py
  backend/community/models.py
  backend/community/serializers.py
  backend/community/views.py
  backend/db.sqlite3
Labels: 🪄 Feature

#6 GG-FE vue 초기 세팅
  .DS_Store
  frontend/.gitignore
  frontend/README.md
  frontend/babel.config.js
  frontend/jsconfig.json
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/src/App.vue
  frontend/src/assets/image/logo1.png
  frontend/src/assets/image/logo2.png
  frontend/src/assets/sass/base/_colors.scss
  frontend/src/assets/sass/base/_flex.scss
  frontend/src/assets/sass/base/_typography.scss
  frontend/src/assets/sass/components/_buttons.scss
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/router/routes.js
  frontend/src/views/MainPage.vue
  frontend/vue.config.js
Labels: 👷 Build

#7 GG-BE accounts 코드 수정 및 게시글 포인트 조회 기능 구현
  backend/GameGenie/__pycache__/__init__.cpython-312.pyc
  backend/GameGenie/__pycache__/settings.cpython-312.pyc
  backend/GameGenie/__pycache__/urls.cpython-312.pyc
  backend/GameGenie/__pycache__/wsgi.cpython-312.pyc
  backend/GameGenie/settings.py
  backend/accounts/__pycache__/__init__.cpython-312.pyc
  backend/accounts/__pycache__/admin.cpython-312.pyc
  backend/accounts/__pycache__/apps.cpython-312.pyc
  backend/accounts/__pycache__/models.cpython-312.pyc
  backend/accounts/__pycache__/serializers.cpython-312.pyc
  backend/accounts/__pycache__/urls.cpython-312.pyc
  backend/accounts/__pycache__/views.cpython-312.pyc
  backend/accounts/migrations/__pycache__/0001_initial.cpython-312.pyc
  backend/accounts/migrations/__pycache__/__init__.cpython-312.pyc
  backend/accounts/views.py
  backend/community/__pycache__/__init__.cpython-312.pyc
  backend/community/__pycache__/admin.cpython-312.pyc
  backend/community/__pycache__/apps.cpython-312.pyc
  backend/community/__pycache__/filters.cpython-312.pyc
  backend/community/__pycache__/models.cpython-312.pyc
  backend/community/__pycache__/serializers.cpython-312.pyc
  backend/community/__pycache__/urls.cpython-312.pyc
  backend/community/__pycache__/views.cpython-312.pyc
  backend/community/migrations/0002_alter_comment_unique_together.py
  backend/community/migrations/0003_remove_comment_comments_upvotes_and_more.py
  backend/community/migrations/__pycache__/0001_initial.cpython-312.pyc
  backend/community/migrations/__pycache__/0002_alter_comment_unique_together.cpython-312.pyc
  backend/community/migrations/__pycache__/0003_remove_comment_comments_upvotes_and_more.cpython-312.pyc
  backend/community/migrations/__pycache__/__init__.cpython-312.pyc
  backend/community/models.py
  backend/community/serializers.py
  backend/community/views.py
  backend/db.sqlite3
Labels: 🐞 BugFix, 🪄 Feature

#11 GG-FE route 설정
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/sass/base/_colors.scss
  frontend/src/assets/sass/base/_typography.scss
  frontend/src/assets/sass/main.scss
  frontend/src/layout/TheFooter.vue
  frontend/src/layout/TheLayout.vue
  frontend/src/layout/TheNavbar.vue
  frontend/src/layout/dashboard/DefaultDashboard.vue
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/router/routes.js
  frontend/src/router/routes/accountRoutes.js
  frontend/src/router/routes/communityRoutes.js
  frontend/src/router/routes/defaultRoutes.js
  frontend/src/views/MainPage.vue
  frontend/src/views/account/LoginPage.vue
  frontend/src/views/account/SignupPage.vue
  frontend/src/views/community/CommunityMainPage.vue
  frontend/vue.config.js
Labels: 🪄 Feature, 👷 Build

#13 GG-BE 게임 정보 수집시 쿠키를 통한 연령확인우회 기능 추가
  backend/.gitignore
  backend/GameGenie/__pycache__/__init__.cpython-312.pyc
  backend/GameGenie/__pycache__/settings.cpython-312.pyc
  backend/GameGenie/__pycache__/urls.cpython-312.pyc
  backend/GameGenie/__pycache__/wsgi.cpython-312.pyc
  backend/accounts/__pycache__/__init__.cpython-312.pyc
  backend/accounts/__pycache__/admin.cpython-312.pyc
  backend/accounts/__pycache__/apps.cpython-312.pyc
  backend/accounts/__pycache__/models.cpython-312.pyc
  backend/accounts/__pycache__/serializers.cpython-312.pyc
  backend/accounts/__pycache__/urls.cpython-312.pyc
  backend/accounts/__pycache__/views.cpython-312.pyc
  backend/accounts/migrations/__pycache__/0001_initial.cpython-312.pyc
  backend/accounts/migrations/__pycache__/__init__.cpython-312.pyc
  backend/community/__pycache__/__init__.cpython-312.pyc
  backend/community/__pycache__/admin.cpython-312.pyc
  backend/community/__pycache__/apps.cpython-312.pyc
  backend/community/__pycache__/filters.cpython-312.pyc
  backend/community/__pycache__/models.cpython-312.pyc
  backend/community/__pycache__/serializers.cpython-312.pyc
  backend/community/__pycache__/urls.cpython-312.pyc
  backend/community/__pycache__/views.cpython-312.pyc
  backend/community/migrations/__pycache__/0001_initial.cpython-312.pyc
  backend/community/migrations/__pycache__/0002_alter_comment_unique_together.cpython-312.pyc
  backend/community/migrations/__pycache__/0003_remove_comment_comments_upvotes_and_more.cpython-312.pyc
  backend/community/migrations/__pycache__/__init__.cpython-312.pyc
  backend/db.sqlite3
  backend/scrapesteam.js
  requirements.txt
Labels: 🪄 Feature

#15 GG-FE main page 구현 완료
  .DS_Store
  frontend/src/App.vue
  frontend/src/assets/image/searchIcon.png
  frontend/src/layout/dashboard/DefaultDashboard.vue
  frontend/src/views/MainPage.vue
Labels: 🪄 Feature

#16 GG-FE login page 구현 및 run serve 문제 해결
  frontend/src/assets/image/loginIdIcon.png
  frontend/src/assets/image/loginPasswordIcon.png
  frontend/src/assets/sass/base/_typography.scss
  frontend/src/layout/TheAccountLayout.vue
  frontend/src/layout/TheAccountNavbar.vue
  frontend/src/layout/TheNavbar.vue
  frontend/src/main.js
  frontend/src/router/routes.js
  frontend/src/views/account/LoginPage.vue
Labels: 🐞 BugFix, 🪄 Feature

#17 GG-FE 회원가입 페이지 구현
  frontend/src/assets/image/account/emailIcon.png
  frontend/src/assets/image/account/idIcon.png
  frontend/src/assets/image/account/nicknameIcon.png
  frontend/src/assets/image/account/passwordIcon.png
  frontend/src/assets/image/account/profileImgIcon.png
  frontend/src/views/account/LoginPage.vue
  frontend/src/views/account/SignupPage.vue
Labels: 🪄 Feature

#18 GG-FE community detail page 추가
  frontend/src/router/routes/communityRoutes.js
  frontend/src/views/community/CommunityDetailPage.vue
Labels: 🪄 Feature

#22 GG-FE search bar 스타일 수정 및 검색 단어에 알맞은 추천 기능 적용
  frontend/src/views/MainPage.vue
Labels: 🐞 BugFix, 🎨 Style

#23 GG-FE 검색어 추천 창 활성화 시 화면이 올라가는 이슈 해결
  frontend/src/layout/dashboard/MainDashboard.vue
  frontend/src/router/routes/defaultRoutes.js
  frontend/src/views/MainSearchPage.vue
  frontend/src/views/RecommendPage.vue
Labels: 🐞 BugFix

#24 GG-FE 로고 이름 변경에 따른 코드 수정
  frontend/src/assets/image/logo.png
  frontend/src/assets/image/logo1.png
  frontend/src/layout/TheAccountNavbar.vue
  frontend/src/layout/TheNavbar.vue
  frontend/src/views/MainSearchPage.vue
Labels: 🗂️ etc

#27 GG-BE 로그인 회원가입 벡엔드 연결
  backend/accounts/views.py
  config.py
  frontend/src/views/account/LoginPage.vue
  frontend/src/views/account/SignupPage.vue
Labels: 🪄 Feature, 🎨 Style

#29 GG-FE 회원가입 성공 페이지 생성 및 router 설정
  frontend/src/layout/TheFooter.vue
  frontend/src/router/routes.js
  frontend/src/router/routes/accountRoutes.js
Labels: 🪄 Feature

#31 GG-FE 회원가입 성공 시 로그인 페이지로 가도록 구현
  frontend/src/router/routes/accountRoutes.js
  frontend/src/views/account/SignupPage.vue
Labels: 🪄 Feature

#32 GG-FE 로그인 실패시 에러 메세지 표시
  frontend/src/views/account/LoginPage.vue
Labels: 🪄 Feature

#33 GG-FE 로그인, 회원가입, 메인 검색 페이지 스타일 수정
  frontend/src/layout/dashboard/MainDashboard.vue
  frontend/src/views/account/LoginPage.vue
  frontend/src/views/account/SignupPage.vue
Labels: 🎨 Style

#34 GG-BE : 커뮤니티 페이징 및 정렬 / 댓글 페이징 / 이미지 및 동영상 첨부 필드 추가 및 패키지 설치
  backend/GameGenie/settings.py
  backend/community/migrations/0006_community_image_community_video.py
  backend/community/models.py
  backend/community/views.py
Labels: 🪄 Feature

#37 GG-FE navbar 및 커뮤니티 메인 페이지 수정
  .DS_Store
  frontend/src/assets/sass/base/_colors.scss
  frontend/src/components/Dropdown.vue
  frontend/src/layout/TheNavbar.vue
  frontend/src/layout/dashboard/DefaultDashboard.vue
  frontend/src/views/community/CommunityCreatePage.vue
  frontend/src/views/community/CommunityMainPage.vue
Labels: 📚 etc

#38 GG-FE 페이지에 따른 footer 색 변경 스타일 구현
  README.md
  frontend/src/layout/TheFooter.vue
Labels: 🎨 Style

#40 GG-FE 커뮤니티메인 페이지 수정
  README.md
  backend/community/filters.py
  backend/community/models.py
  frontend/src/views/community/CommunityCreatePage.vue
  frontend/src/views/community/CommunityMainPage.vue
Labels: 🪄 Feature

#44 GG-FE router 수정 및 코드 변경
  frontend/src/router/routes/communityRoutes.js
  frontend/src/views/community/CommunityMainPage.vue
Labels: 📚 etc

#45 GG-BE 게임 가격을 제대로 가져오지 못하는 버그 수정
  backend/package-lock.json
  backend/package.json
  backend/recommendations/steam_api.py
  backend/recommendations/views.py
Labels: 🐞 BugFix

#46 GG-FE 커뮤니티메인 게시글 리스트 표시구현
  backend/accounts/serializers.py
  backend/accounts/urls.py
  backend/accounts/views.py
  backend/community/views.py
  frontend/src/views/community/CommunityCreatePage.vue
  frontend/src/views/community/CommunityDetailPage copy.vue
  frontend/src/views/community/CommunityMainPage.vue
Labels: 🪄 Feature

#51 GG-FE 게임 추천 화면 UI 변경
  backend/recommendations/steam_api.py
  backend/recommendations/views.py
  frontend/src/views/GameCard.vue
  frontend/src/views/RecommendPage.vue
Labels: 🪄 Feature
