Repository sieuno3o/GameGenie, pull requests merged in 2024-06, with the labels that each got.

#53 GG-BE 게임 즐겨찾기 기능 추가, 글 등록 버그 수정
  backend/accounts/migrations/0001_initial.py
  backend/accounts/serializers.py
  backend/community/migrations/0001_initial.py
  backend/recommendations/migrations/0001_initial.py
  backend/recommendations/models.py
  backend/recommendations/serializers.py
  backend/recommendations/urls.py
  backend/recommendations/views.py
  frontend/src/api.js
  frontend/src/views/GameCard.vue
  frontend/src/views/MainSearchPage.vue
  frontend/src/views/RecommendPage.vue
  frontend/src/views/community/CommunityCreatePage.vue
Labels: 🐞 BugFix, 🪄 Feature

#55 GG-FE 추천 페이지 수정 및 기능 구현 시도
  frontend/src/views/GameCard.vue
  frontend/src/views/RecommendPage.vue
Labels: 🪄 Feature, 🎨 Style

#57 GG-FE 커뮤니티 메인화면 카테고리 드롭박스 구현
  backend/community/views.py
  frontend/src/views/community/CommunityDetailPage.vue
  frontend/src/views/community/CommunityMainPage.vue
Labels: 🪄 Feature

#56 GG-FE: 커뮤니티 디테일 페이지 추가 구현
  frontend/src/views/community/CommunityDetailPage.vue
Labels: 🪄 Feature

#59 GG-FE navbar dropdown
  frontend/src/layout/TheNavbar.vue
Labels: 🪄 Feature, 🎨 Style

#60 GG-FE navbar 코드 오류 수정
  frontend/src/layout/TheNavbar.vue
Labels: 📚 etc

#61 GG-FE navbar 수정
  frontend/src/layout/TheNavbar.vue
Labels: 🪄 Feature, 🎨 Style

#69 GG-FE 게임 추천 갯수에 상관없이 카드 크기 일정하게 수정
  frontend/src/views/RecommendPage.vue
Labels: 🐞 BugFix

#71 GG-FE #63 - 로그인 하지 않은 상태에서 글작성 클릭 시 alert 띄워주고 확인 누르면 로그인 페이지로 갈 수 있도록
  frontend/src/views/community/CommunityMainPage.vue
Labels: 🪄 Feature

#72 GG-FE #64-로그인창에서 아이디 비밀번호 입력 후 꼭 버튼을 클릭하는 것이 아닌 엔터로도 가능하도록
  frontend/src/views/account/LoginPage.vue
Labels: 🐞 BugFix

#73 GG-BE nickname 모델 추가 및 회원가입시 nickname을 필드로 전송하게 수정
  backend/accounts/migrations/0001_initial.py
  backend/accounts/models.py
  backend/accounts/serializers.py
  backend/accounts/views.py
  backend/community/migrations/0001_initial.py
  backend/recommendations/migrations/0001_initial.py
  frontend/src/router/routes/accountRoutes.js
  frontend/src/views/account/ProfilePage.vue
  frontend/src/views/account/SignupPage.vue
Labels: 🐞 BugFix, 🪄 Feature

#74 GG-FE navbar에 username 대신 nickname 표시, 프로필 수정 시 username 대신 nickname이 변경되도록 수정
  frontend/src/layout/TheNavbar.vue
  frontend/src/views/account/LoginPage.vue
  frontend/src/views/account/ProfilePage.vue
Labels: 🐞 BugFix, 🪄 Feature

#77 GG-FE 사용자 정보를 로컬에 저장하는 대신 토큰 전달로 인증방식을 변경
  backend/accounts/urls.py
  backend/accounts/views.py
  frontend/src/api.js
  frontend/src/layout/TheNavbar.vue
  frontend/src/views/account/LoginPage.vue
  frontend/src/views/account/ProfilePage.vue
  frontend/src/views/community/CommunityCreatePage.vue
Labels: 🪄 Feature

#79 GG-FE 디테일 페이지 수정하기 구현
  backend/community/views.py
  frontend/src/views/community/CommunityDetailPage.vue
Labels: 🪄 Feature

#81 GG-FE 프로필 url이 undefined로 표시되는 문제 수정
  backend/accounts/views.py
  frontend/src/layout/TheNavbar.vue
  frontend/src/router/routes/accountRoutes.js
  frontend/src/views/RecommendPage.vue
  frontend/src/views/account/LoginPage.vue
  frontend/src/views/account/ProfilePage.vue
Labels: 🐞 BugFix

#83 GG-FE: URL/imige 업로드 기능 추가
  frontend/src/views/community/CommunityCreatePage.vue
Labels: 🪄 Feature

#88 FE-GG 스타일 수정 및 코드 리팩토링
  backend/accounts/models.py
  frontend/src/layout/TheFooter.vue
  frontend/src/layout/TheNavbar.vue
  frontend/src/layout/dashboard/DefaultDashboard.vue
  frontend/src/layout/dashboard/MainDashboard.vue
  frontend/src/router/routes/accountRoutes.js
  frontend/src/router/routes/defaultRoutes.js
  frontend/src/views/RecommendPage.vue
Labels: 🎨 Style, 📚 etc

#90 GG-FE 게임 추천 페이지 기능적 오류 해결
  frontend/src/views/RecommendPage.vue
  frontend/src/views/account/ProfilePage.vue
Labels: 🐞 BugFix

#91 GG-FE 카드 정보가 안불러와지는 이슈 수정
  frontend/src/views/GameCard.vue
  frontend/src/views/account/ProfilePage.vue
Labels: 🐞 BugFix

#92 GG-FE 즐겨찾기 카드 수정 및 내 정보 페이지 즐겨찾기란 수정
  frontend/src/layout/dashboard/DefaultDashboard.vue
  frontend/src/layout/dashboard/MainDashboard.vue
  frontend/src/layout/dashboard/RecommendDashBoard.vue
  frontend/src/views/GameCard.vue
  frontend/src/views/RecommendPage.vue
  frontend/src/views/account/ProfilePage.vue
Labels: 🐞 BugFix, 🪄 Feature, 🎨 Style

#93 GG-FE 프로필이미지추가 및 수정 구현
  frontend/src/views/account/ProfilePage.vue
Labels: 🪄 Feature

#94 GG-FE 카드가 겹치는 오류 수정, 마이페이지 스타일 수정
  frontend/src/views/GameCard.vue
  frontend/src/views/account/ProfilePage.vue
Labels: 🐞 BugFix, 🎨 Style

#95 GG-BE accounts 시리얼라이저 수정
  backend/accounts/serializers.py
Labels: 🪄 Feature

#96 GG-FE 댓글 닉네임 옆 프로필이미지 표시
  frontend/src/views/community/CommunityDetailPage.vue
Labels: 🪄 Feature

#97 GG-FE 글 작성자만 수정, 삭제 가능하게 변경
  backend/accounts/serializers.py
  backend/community/serializers.py
  backend/community/views.py
  frontend/src/views/community/CommunityDetailPage.vue
Labels: 🐞 BugFix

#106 GG-FE 댓글 수정, 삭제 기능 추가
  backend/GameGenie/settings.py
  backend/community/models.py
  backend/community/urls.py
  backend/community/views.py
  frontend/src/views/community/CommunityDetailPage.vue
Labels: 🪄 Feature

#107 GG-FE 커뮤니티 글 작성 페이지 스타일 변경
  frontend/src/api.js
  frontend/src/assets/sass/base/_colors.scss
  frontend/src/assets/sass/base/_typography.scss
  frontend/src/components/Dropdown.vue
  frontend/src/layout/TheNavbar.vue
  frontend/src/views/account/LoginPage.vue
  frontend/src/views/account/ProfilePage.vue
  frontend/src/views/account/SignupPage.vue
  frontend/src/views/community/CommunityCreatePage.vue
Labels: 🎨 Style

#109 GG-FE 즐겨찾기 존재하지 않을 때 스타일 수정
  frontend/src/views/account/ProfilePage.vue
Labels: 🎨 Style

#110 GG-FE 마이 페이지 스타일 추가 변경
  frontend/src/views/account/ProfilePage.vue
Labels: 🎨 Style

#108 GG - BE : 이미지파일 업로드 이슈
  backend/GameGenie/settings.py
  backend/accounts/migrations/0001_initial.py
  backend/accounts/models.py
  backend/accounts/serializers.py
  backend/accounts/views.py
  backend/community/migrations/0001_initial.py
  backend/community/serializers.py
  backend/recommendations/migrations/0001_initial.py
  frontend/src/views/account/LoginPage.vue
  frontend/src/views/account/ProfilePage.vue
  frontend/src/views/account/SignupPage.vue
  frontend/src/views/community/CommunityDetailPage.vue
Labels: 🥹 help wanted

#111 GG-FE #99-게시글 조회수 구현
  backend/accounts/migrations/0001_initial.py
  backend/community/migrations/0001_initial.py
  backend/community/models.py
  backend/community/serializers.py
  backend/community/views.py
  backend/recommendations/migrations/0001_initial.py
  frontend/src/views/community/CommunityDetailPage.vue
  frontend/src/views/community/CommunityMainPage.vue
Labels: 🪄 Feature

#112 GG-FE 커뮤니티 게시글 목록 페이지 스타일 구현
  frontend/src/assets/sass/base/_typography.scss
  frontend/src/views/community/CommunityDetailPage.vue
  frontend/src/views/community/CommunityMainPage.vue
Labels: 🪄 Feature, 🎨 Style

#116 GG-FE 커뮤니티 글 작성 페이지 링크 입력칸 비활성화
  frontend/src/views/community/CommunityCreatePage.vue
Labels: 🎨 Style

#118 GG-FE 글 작성시 필수 항목 표시 수정
  frontend/src/views/community/CommunityCreatePage.vue
Labels: 🐞 BugFix

#123 GG-FE 커뮤니티 디테일 페이지 수정
  frontend/src/views/account/ProfilePage.vue
  frontend/src/views/community/CommunityDetailPage.vue
  frontend/src/views/community/CommunityMainPage.vue
Labels: 🪄 Feature, 🎨 Style

#124 GG-FE #119-댓글 수 구현
  backend/accounts/migrations/0001_initial.py
  backend/community/migrations/0001_initial.py
  backend/community/serializers.py
  backend/community/views.py
  backend/recommendations/migrations/0001_initial.py
  frontend/src/views/community/CommunityDetailPage.vue
  frontend/src/views/community/CommunityMainPage.vue
Labels: 🪄 Feature

#126 GG-FE 글 작성, 수정 후 바로 디테일 페이지로 이동하도록 수정
  frontend/src/views/community/CommunityCreatePage.vue
Labels: 🐞 BugFix

#127 GG-BE 게임 추천 기능 이용시 의미없는 검색어를 입력하면 에러메세지를 반환하도록 수정
  backend/community/views.py
  backend/recommendations/views.py
  frontend/src/views/RecommendPage.vue
Labels: 🪄 Feature

#128 GG-FE 댓글 페이지네이션 구현
  frontend/src/views/community/CommunityDetailPage.vue
Labels: 🪄 Feature

#129 GG-FE 게시글 상세 페이지에서 전체 댓글 수 표시
  frontend/src/views/community/CommunityDetailPage.vue
Labels: 🪄 Feature

#130 GG-FE 커뮤니티 디테일 페이지 스타일 수정
  frontend/src/views/community/CommunityDetailPage.vue
Labels: 🎨 Style

#131 GG-BE 게임 추천 로직 수정
  backend/recommendations/views.py
  frontend/src/views/RecommendPage.vue
Labels: 🪄 Feature

#132 GG-BE 게임 추천 로직 수정
  backend/recommendations/views.py
Labels: 🐞 BugFix

#133 GG-FE 댓글 페이지네이션 스타일 수정
  frontend/src/views/community/CommunityDetailPage.vue
Labels: 🎨 Style

#135 GG-FE 커뮤니티 카테고리 이슈 해결
  frontend/src/views/community/CommunityMainPage.vue
Labels: 🐞 BugFix

#138 GG-FE signup 페이지 아이디, 이메일 중복 처리
  frontend/src/views/account/SignupPage.vue
Labels: 🪄 Feature

#139 GG-FE 게임 추천 메세지 표시 개선
  backend/recommendations/views.py
  frontend/src/views/RecommendPage.vue
Labels: 🪄 Feature

#140 GG-FE 유튜브 임베디드 기능 추가
  backend/accounts/views.py
  frontend/src/views/community/CommunityDetailPage.vue
Labels: 🪄 Feature

#141 GG-FE 유효성 검사에서 줄바꿈 허용
  backend/community/serializers.py
  frontend/src/views/community/CommunityCreatePage.vue
Labels: 🐞 BugFix
